#!/bin/bash

# Use of seq command with for loop
for x in `seq 10 5 30`; 
do
	echo $x
done

# Use of a set of commands and display their output with for loop
for command in ls pwd date whoami
do
	echo "--------$command--------"
	$command
done

# Listing all directories using for loop

for item in *
do
   if [ -d $item ]
   then
      echo $item
   fi
done
